services:
    # Database
    db:
        image: mysql:8.3
        container_name: hololive-db
        restart: always
        environment:
            MYSQL_DATABASE: "hololive"
            MYSQL_USER: "forge"
            MYSQL_PASSWORD: "forge"
            MYSQL_ROOT_PASSWORD: "forge"
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data: {}
